### ISSUE TITLE
Not accurate

### ISSUE THREAD

**Issue by Nikit333** [DoubangoTelecom/FaceLivenessDetection-SDK#3] opened 2021-04-23 09:06 UTC
Hello,
I have tested your implementation but it's not accurate on some of my dataset.
Are you planning to improve the accuracy?

![image](https://user-images.githubusercontent.com/80960135/115805737-244b0a00-a418-11eb-9b6f-ec7241f61e2c.png)

![image](https://user-images.githubusercontent.com/80960135/115806322-206bb780-a419-11eb-8bf7-02b306c21ec7.png)

![image](https://user-images.githubusercontent.com/80960135/115806432-56a93700-a419-11eb-8f1c-54388be8c4ca.png)

![image](https://user-images.githubusercontent.com/80960135/115806695-d33c1580-a419-11eb-868a-cf6c75de0109.png)

**Comment by DoubangoTelecom** [comment] 2021-04-23 10:05
Please share these 4 images and we'll check

**Comment by DoubangoTelecom** [comment] 2021-04-23 19:06
The support team has checked your images. They do not match the requirements (https://www.doubango.org/SDKs/face-liveness/docs/Improving_recall.html#the-7-commandments). The face must be at least `600px`, yours are 100 to 200px. Also, the image has to be 720p. Your images are clearly close to 224px. 
These requirements are important to have accurate texture analysis and 3D depth estimation. If this was a commercial deployment, then we would reject your images without any analysis. So, **this is not a bug**.
We'll continue to accept these images but we'll change the result from `s_genuine` to `s_becareful` to signal that the image doesn't match the requirements but let it pass to ease testing. See issue #4
Duplicate of #4

**Comment by DoubangoTelecom** [comment] 2021-04-23 19:31
You may try to resize the image to match the requirements to see if you can crack the system. In real life the only way to input images is via the camera stream. We allow drag&drop to ease testing but a commercial product won't allow it. So, the only way to claim that the implementation is not accurate is if you manage to crack it using the camera and matching the requirements.

**Comment by Nikit333** [comment] 2021-04-26 08:22
.

**Comment by DoubangoTelecom** [comment] 2021-04-26 19:28
We have updated the deep learning models to fix the issue. 
Reopening the issue to get feedbacks.
You can test with your images it should work even if the requirements are not completely respected.

**Comment by sybrin-innovations** [comment] 2021-04-29 08:57
@DoubangoTelecom Do you have this model on  Web.api you can share for testing?

You can email me on silentanamika@gmail.com
 
I am keen to test and provide feedback as well as share with you our opportunities.

**Comment by JinXue-wijong** [comment] 2021-04-30 14:29
Some false images passed in API testing.

![image](https://user-images.githubusercontent.com/37200250/116709396-3540e000-aa03-11eb-80b2-f2b15fd7f183.png)

**Comment by JinXue-wijong** [comment] 2021-04-30 16:14
Web Demo doesn't work well on some images.
Some spoof images accepted by your API.
I removed image for some privacy reason.
@DoubangoTelecom  you can check mail box.

**Comment by DoubangoTelecom** [comment] 2021-04-30 18:13
> Web Demo doesn't work well on some images.
> Some spoof images accepted by your API.
> I removed image for some privacy reason.
> @DoubangoTelecom you can check mail box.

As already explained, use the camera to input the images. Don't use drag&drop. A commercial app won't allow drag&drop, we allow it to ease testing. A jpeg file stored in your pc can be resized and edited.
Also, we are continuously updating the models, you can try again in few days and it'll probably work better.

**Comment by DoubangoTelecom** [comment] 2021-04-30 18:19
> Web Demo doesn't work well on some images.
> Some spoof images accepted by your API.
> I removed image for some privacy reason.
> @DoubangoTelecom you can check mail box.

Quote from issue #1: "If you have a spoof reported as genuine, please report only if you've used the camera to input the image. Drag&Drop is enabled to ease testing, a commercial product would not allow it."

**Comment by DoubangoTelecom** [comment] 2021-04-30 18:21
> Web Demo doesn't work well on some images.
> Some spoof images accepted by your API.
> I removed image for some privacy reason.
> @DoubangoTelecom you can check mail box.

Quote from issue #1: "If you have a spoof reported as genuine, please report only if you're using the camera to input the image. Drag&Drop is enabled to ease testing, a commercial product would not allow it."

**Comment by JinXue-wijong** [comment] 2021-04-30 18:30
Please check image if you logged files.
It's image from iPhone12 camera, not edited at all.

**Comment by DoubangoTelecom** [comment] 2021-04-30 19:39
> Please check image if you logged files.
> It's image from iPhone12 camera, not edited at all.

We had reports about iOS in issue #2, was tested with iPad Air 2 and closed. I'll reopen the issue.

**Comment by Nikit333** [comment] 2021-07-01 02:28
Hi, Doubango
I am a little confused.
Almost all real images are marked as fake.
I am not sure what I did wrong.

![image](https://user-images.githubusercontent.com/80960135/124055691-ee995180-da56-11eb-9a42-debeddec7670.png)

![image](https://user-images.githubusercontent.com/80960135/124055737-07096c00-da57-11eb-81b6-435a96a39bc7.png)

**Comment by Nikit333** [comment] 2021-07-01 02:36
Mamodou not respond on linkedIn.

**Comment by DoubangoTelecom** [comment] 2021-07-01 03:08
> Hi, Doubango
> I am a little confused.
> Almost all real images are marked as fake.
> I am not sure what I did wrong.
> 
> ![image](https://user-images.githubusercontent.com/80960135/124055691-ee995180-da56-11eb-9a42-debeddec7670.png)
> 
> ![image](https://user-images.githubusercontent.com/80960135/124055737-07096c00-da57-11eb-81b6-435a96a39bc7.png)

Check https://www.doubango.org/SDKs/face-liveness/docs/Improving_recall.html#the-7-commandments

**Closed by DoubangoTelecom** 2021-07-01 03:08 UTC
Labels: good first issue

**Comment by Nikit333** [comment] 2021-07-01 03:11
What's this then?
![image](https://user-images.githubusercontent.com/80960135/124059059-0d9ae200-da5d-11eb-9ffa-b56db9f006b8.png)

**Comment by Nikit333** [comment] 2021-07-01 03:13
Other implementations easily detect that as live.
How can you say yours outperform others without benchmarking their own dataset?

![image](https://user-images.githubusercontent.com/80960135/124059173-358a4580-da5d-11eb-8d6f-928c1ed7a538.png)

**Comment by DoubangoTelecom** [comment] 2021-07-01 03:15
> What's this then?
> ![image](https://user-images.githubusercontent.com/80960135/124059059-0d9ae200-da5d-11eb-9ffa-b56db9f006b8.png)

You can provide images with faces at any distance and this will not fool the implementation. This is what it means. When the face is overexposed to lighting like the two faces you have provided, then it's rejected.

**Comment by Nikit333** [comment] 2021-07-01 03:17
Haha.
What about say 'FAKE' to all images?

**Comment by DoubangoTelecom** [comment] 2021-07-01 03:17
> Other implementations easily detect that as live.
> How can you say yours outperform others without benchmarking their own dataset?
> 
> ![image](https://user-images.githubusercontent.com/80960135/124059173-358a4580-da5d-11eb-8d6f-928c1ed7a538.png)

Now you're just making thinks up. The listed implementations only accept video streams. You cannot say they work with these images.

**Comment by Nikit333** [comment] 2021-07-01 03:19
Then how to use for general face recognition?

![image](https://user-images.githubusercontent.com/80960135/124059757-32438980-da5e-11eb-84a3-4ab9a66ef4be.png)

**Comment by DoubangoTelecom** [comment] 2021-07-01 03:19
> Haha.
> What about say 'FAKE' to all images?

If that was the case, then it won't be used on multiple commercial implementations. I understand you're upset about the stress test we did on your application (https://www.doubango.org/SDKs/face-liveness/docs/Testing_the_competition.html#minivision-ai-turingtech-vip)

**Comment by DoubangoTelecom** [comment] 2021-07-01 03:24
> Please check image if you logged files.
> It's image from iPhone12 camera, not edited at all.

Should be fixed by latest models

**Comment by Nikit333** [comment] 2021-07-01 03:24
I don't do that kind of stress-test against others.
Please respect others.
If I decided, I can make such report for your implementation easily.

**Comment by DoubangoTelecom** [comment] 2021-07-01 03:31
> I don't do that kind of stress-test against others.
> Please respect others.
> If I decided, I can make such report for your implementation easily.

Almost every research paper has a section where the writer compares his/her implementation to others. This is not disrespect but how competition works. We were very happy when you provided early feedbacks and it helped up improve the accuracy. We'll be happy if you find issues in the product. It'll help us. So, please move and write a report highlighting the issues.

**Comment by DoubangoTelecom** [comment] 2021-07-01 03:38
> I don't do that kind of stress-test against others.
> Please respect others.
> If I decided, I can make such report for your implementation easily.

Y don't do that kind of stress-test against others but you still their work. First, you did it with Huawei then with Minivision-ai. You stole their work (no credit to their project), then you spammed them saying your product is better. It's shameful.

**Comment by DoubangoTelecom** [comment] 2021-07-01 03:50
> I don't do that kind of stress-test against others.
> Please respect others.
> If I decided, I can make such report for your implementation easily.

Respect? Here is the list of some projects you have shamefully spammed:
- https://github.com/syaringan357/Android-MobileFaceNet-MTCNN-FaceAntiSpoofing/issues/26
- https://github.com/deepcam-cn/Face-Anti-spoofing.pytorch/issues/24
- https://github.com/clks-wzz/FAS-SGTD/issues/23
- https://github.com/AlexanderParkin/ChaLearn_liveness_challenge/issues/27
- https://github.com/SeuTao/CVPR19-Face-Anti-spoofing/issues/27
- https://github.com/zeusees/Zeusee-Face-Anti-spoofing/issues/34
- https://github.com/SoftwareGift/FeatherNets_Face-Anti-spoofing-Attack-Detection-Challenge-CVPR2019/issues/95
- https://github.com/zeusees/HyperFAS/issues/15
- https://github.com/kprokofi/light-weight-face-anti-spoofing/issues/15
